# Generated by Django 5.2 on 2025-05-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Emotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emoji",
                    models.CharField(max_length=255, verbose_name="감자 이모지 url"),
                ),
                ("emotion", models.CharField(max_length=10, verbose_name="감정")),
            ],
        ),
    ]
