# Generated by Django 5.2 on 2025-05-12 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Emotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emoji",
                    models.CharField(
                        help_text="예: /static/emotions/1.png",
                        max_length=255,
                        verbose_name="감자 이모지 url",
                    ),
                ),
                (
                    "emotion",
                    models.CharField(blank=True, max_length=10, verbose_name="감정"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmotionData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "emotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="emotion.emotion",
                    ),
                ),
            ],
            options={
                "verbose_name": "감정 사용 기록",
                "verbose_name_plural": "감정 사용 기록들",
            },
        ),
    ]
