# Generated by Django 5.emotions on 2025-05-06 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emotion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmotionData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "emotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="emotion.emotion",
                    ),
                ),
            ],
            options={
                "verbose_name": "감정 사용 기록",
                "verbose_name_plural": "감정 사용 기록들",
            },
        ),
    ]
