# Generated by Django 5.2 on 2025-05-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emotion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emotion",
            name="emoji",
            field=models.CharField(
                help_text="예: 1.png", max_length=255, verbose_name="감자 이모지 url"
            ),
        ),
    ]
