# Generated by Django 5.emotions on 2025-05-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_socialaccount_provider_user_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialaccount",
            name="provider",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to="profiles/"
            ),
        ),
    ]
