# Generated by Django 5.emotions on 2025-05-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_socialaccount_provider_alter_user_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile",
            field=models.ImageField(
                blank=True, max_length=1024, null=True, upload_to="profiles/"
            ),
        ),
    ]
