# Generated by Django 5.emotions on 2025-05-09 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0002_alter_like_diary"),
        ("diary", "0002_create_emotions"),
    ]

    operations = []
