# Generated by Django 5.2 on 2025-05-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diaryimage",
            name="image_url",
        ),
        migrations.AddField(
            model_name="diaryimage",
            name="image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="diary_images/",
                verbose_name="Image File",
            ),
        ),
    ]
