# Generated by Django 5.2 on 2025-05-14 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0003_remove_diaryimage_image_url_diaryimage_image"),
        ("emotion", "0002_alter_emotion_emoji"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diaryemotion",
            name="emotion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="emotion.emotion"
            ),
        ),
        migrations.DeleteModel(
            name="Emotion",
        ),
    ]
