# Generated by Django 5.2 on 2025-05-19 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("friends", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="diaryfriend",
            old_name="friend_user_id",
            new_name="friend_user",
        ),
    ]
