# Generated by Django 5.2 on 2025-05-20 01:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("friends", "0002_rename_friend_user_id_diaryfriend_friend_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="diaryfriend",
            unique_together={("user", "friend_user")},
        ),
    ]
