name: Django Project CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DJANGO_SETTINGS_MODULE: config.settings.dev
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Create dev.env file
        run: |
          mkdir -p envs
          echo "DJANGO_SETTINGS_MODULE=config.settings.dev" >> envs/dev.env
          echo "ENV_MODE=dev" >> envs/dev.env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> envs/dev.env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> envs/dev.env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> envs/dev.env
          echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> envs/dev.env
          echo "POSTGRES_HOST=localhost"                          >> envs/dev.env
          echo "POSTGRES_PORT=5432"                               >> envs/dev.env

      - name: Wait for PostgreSQL to be ready
        run: sleep 10

      - name: Install Packages & Libraries
        run: |
          poetry install

      - name: Run code format check (black & isort)
        run: |
          poetry run black --check .
          poetry run isort --check-only .

      - name: Run tests
        run: |
          poetry run coverage run --source="config" manage.py test
