name: Django EC2 Deployment

on:
  workflow_run:
    workflows: ["Django Project CI"]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest

    steps:
      - name: EC2 ssh connection and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/TeamProject_BE
            git pull origin main
            
            mkdir -p envs
            echo "DJANGO_SETTINGS_MODULE=config.settings.prod" > envs/prod.env
            echo "ENV_MODE=prod" >> envs/prod.env
            echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> envs/prod.env
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> envs/prod.env
            echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> envs/prod.env
            echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> envs/prod.env
            echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> envs/prod.env
            echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> envs/prod.env

            python3 -m venv venv
            source venv/bin/activate
            pip install poetry
            poetry install --no-interaction --no-ansi
            python manage.py migrate --noinput
            python manage.py collectstatic --noinput

            sudo systemctl restart gunicorn
            sudo systemctl reload nginx